spring:
  datasource:
    name: boot
    url: jdbc:mysql://127.0.0.1:3306/xuan_fruit?autoReconnect=true&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 60000
      # 连接池最大连接数
      maximum-pool-size: 10
      # 从池返回的连接的默认自动提交行为
      auto-commit: true
      # 连接池母子
      pool-name: MyHikariCP
      # 池中连接的最长生命周期-30分钟
      max-lifetime: 1800000
      # 连接超时-30s
      connection-timeout: 30000
      # 连接测试语句
      connection-test-query: SELECT NOW()

  # redis配置
  redis:
    # 是否开启redis缓存
    open: true
    host: 127.0.0.1
    port: 6379
    # 连接超时时长（毫秒）
    timeout: 60000ms
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 5